### ISSUE TITLE
При использовании модуля кеш сохраняется и загружается дважды

### ISSUE THREAD

**Issue by scf2k** [enb-bem/enb-magic-factory#37]
На проекте с подключенным модулем кеш сохраняется дважды: самим enb при завершении сборки и тут https://github.com/enb-bem/enb-magic-factory/blob/master/lib/magic-helper.js#L273
Аналогично дважды загружается перед сборкой https://github.com/enb-bem/enb-magic-factory/blob/master/lib/magic-helper.js#L258

**Comment by andrewblond** [comment]
Должно быть достаточно просто использовать общий инстанс `cacheStorage` не загружая/сохраняя кэш в/из файловой системы. Загрузка и сохранение должны происходить только в платформе.

**Comment by andrewblond** [comment]
Исправлено в версии `v0.4.4`.
